//This class is generated by convert_string.py
//DO NOT modify this class manually

import Foundation

class Text {

    static let BACK = NSLocalizedString("BACK", comment:"")

    static let CANCEL = NSLocalizedString("CANCEL", comment:"")

    static let MSG_FAILED_TO_LOAD = NSLocalizedString("MSG_FAILED_TO_LOAD", comment:"")

    static let OK = NSLocalizedString("OK", comment:"")

    static let OPEN_YOUTUBE = NSLocalizedString("OPEN_YOUTUBE", comment:"")

    static let SEARCH_WORD_CAT = NSLocalizedString("SEARCH_WORD_CAT", comment:"")

    static let SEARCH_WORD_DOG = NSLocalizedString("SEARCH_WORD_DOG", comment:"")

}
